### ISSUE TITLE
kvmhost[0] breaks multi-host inventories

### ISSUE THREAD

**Issue by sluetze** [csmart/ansible-role-virt-infra#37]
Hi again :-),

i have a inventory with multiple kvmhosts
```yaml
kvmhost:
  hosts:
    host0:
    [...]
    host1:
    [...]
```

they are also member of another inventory file, for the "which" (Following guidelines @ https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html#intro-patterns) 
```yaml
prod:
  hosts:
    host1:
dev:
  hosts:
    host0:
```

this results in errors, if i use the role for the prod environment since there is a ton of
`hostvars[groups['kvmhost'][0]]` lookups throughout the role and kvmhost[0] is host0. which just does not exist in dev.
This also invalidates the checks for any multi kvmhost scenario.
I _think_ there _should_ be very small issues when removing most of the lookups and just use the named facts you register.

Since this makes a whopping 140 occurences of that pattern i am not sure if the role was ever intended to do multiple kvm hosts and if a PR implementing this would be welcomed?
